name:                raytrace
version:             0.1.0.0
github:              "edgao/raytrace"
license:             BSD3
author:              "Edward Gao"
maintainer:          "nah"
copyright:           "2020 Edward Gao"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/raytrace#readme>

dependencies:
- base >= 4.7 && < 5
- linear >=1.20.9
- tasty >=1.2.3
- tasty-hunit >=0.10

library:
  source-dirs: src

executables:
  raytrace-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raytrace

tests:
  raytrace-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raytrace
